---
title: 异常
categories: 
- 编程语言
- Java基础
---

**异常的结构**   

<img src="https://img-blog.csdnimg.cn/35b4fb4d41fe41188e407aae7de300e0.png" style="zoom:33%;" />

Exception分两大类：**运行时异常** 和 **非运行时异常**(编译异常)。程序中应当尽可能去处理这些异常。    

**运行时异常**：

都是RuntimeException类及其子类异常，如NullPointerException(空指针异常)、IndexOutOfBoundsException(下标越界异常)等，这些异常是不检查异常，程序中可以选择捕获处理，也可以不处理。

**非运行时异常 （编译异常）**：

是RuntimeException以外的异常，类型上都属于Exception类及其子类。

从程序语法角度讲是必须进行处理的异常，如果不处理，程序就不能编译通过。

如IOException、SQLException等以及用户自定义的Exception异常，一般情况下不自定义检查异常。

**异常处理的机制**

> Throws抛出异常

**如果一个方法可能会出现异常，但没有能力处理这种异常，可以在方法声明处用throws子句来声明抛出异常。**

throws语句用在方法定义时声明该方法要抛出的异常类型，如果抛出的是Exception异常类型，则该方法被声明为抛出所有的异常。

多个异常可使用逗号分割。throws语句的语法格式为：    

```java
 methodname throws Exception1,Exception2,..,ExceptionN  {  }  
```

**使用throws关键字将异常抛给调用者后，如果调用者不想处理该异常，可以继续向上抛出，但最终要有能够处理该异常的调用者。**

> 用throw抛出异常

throw总是出现在方法体中，用来抛出一个Throwable类型的异常。

程序会在throw语句后立即终止，它后面的语句执行不到，然后在包含它的所有try块中（可能在上层调用函数中）从里向外寻找含有与其匹配的catch子句的try块。

```java
public class ExceptionTest02 {
    public static void main(String[] args) throws ArithmeticException{
        System.out.println("程序执行开始的地方...");
        try{
            method1();
            //当这里有异常发生时, 后面的代码也都不会执行, 这里指的就是method1()方法有异常
            //System.out.println("这里的代码不会在执行了...");
        } catch (ArithmeticException e){
            System.out.println("解决异常");
        } finally{
            System.out.println("我是main中finally执行的代码.....");
        }
        System.out.println("main方法执行的最后一个方法....");
    }
 
    public static void method1(){
        int a = 10;
        int b = 0;
        System.out.println("进入异常的开头....");
        throw new ArithmeticException();
        //System.out.println("这里不能再写程序了....");
    }
}
```

**try-catch语句**

在Java中，异常通过**try-catch语句**捕获。

```java
try {  
	// 可能会发生异常的程序代码  
} catch (Type1 id1){  
	// 捕获并处置try抛出的异常类型Type1  
} catch (Type2 id2){  
	 //捕获并处置try抛出的异常类型Type2  
}
```

 **匹配的原则是**：

* **如果抛出的异常对象属于catch子句的异常类，或者属于该异常类的子类**，则认为生成的异常对象与catch块捕获的异常类型相匹配。

**注意**：一旦某个catch捕获到匹配的异常类型，将进入异常处理代码。一经处理结束，就意味着整个try-catch语句结束。其他的catch子句不再有匹配和捕获异常类型的机会。

**try-catch-finally语句**

try-catch语句还可以包括第三部分，就是finally子句。它表示无论是否出现异常，都应当执行的内容。

```java
try {  
	// 可能会发生异常的程序代码  
} catch (Type1 id1){  
	// 捕获并处置try抛出的异常类型Type1  
} catch (Type2 id2){  
	 //捕获并处置try抛出的异常类型Type2  
}finally {  
	// 无论是否发生异常，都将执行的语句块  
} 
```

**try、catch、finally语句块的执行顺序:**

* 当try没有捕获到异常时：
  * try语句块中的语句逐一被执行，程序将跳过catch语句块，执行finally语句块和其后的语句；

* 当try捕获到异常，catch语句块里没有处理此异常的情况：
  * 此异常将会抛给JVM处理，finally语句块里的语句还是会被执行，但finally语句块后的语句不会被执行；

* 当try捕获到异常，catch语句块里有处理此异常的情况：
  * 在try语句块中是按照顺序来执行的，当执行到某一条语句出现异常时，程序将跳到catch语句块，并与catch语句块逐一匹配，找到与之对应的处理程序，其他的catch语句块将不会被执行，而try语句块中，出现异常之后的语句也不会被执行，catch语句块执行完后，执行finally语句块里的语句，最后执行finally语句块后的语句。